version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    working_directory: ~/lunchly
    dependencies:
      pre:
        - npm install npm@5.6.0 -g
        - npm install angular-cli@latest -g
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-node-modules
          command: npm install
      - run:
          name: angular-tests
          command: npm test -- --single-run --no-progress
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
